version: '{build}'
branches:
  only:
  - master

image: Visual Studio 2017

#install:
#  - ps: .\install-vsix-appveyor.ps1

configuration:
- Release

platform: Any CPU

before_build:
- nuget restore

build:
  verbosity: normal

  # scripts to run after build
#after_build:
  #- ps: $($env:IDE_PATH)\devenv.exe GranitEditorSetup\GranitEditorSetup.vdproj /build $($env:CONFIGURATION)

artifacts:
- path: GranitEditorSetup\Release
  name: GranitEditor Installer
- path: GranitXMLEditor\bin\Release
  name: GranitEditor Release Deployment
- path: GranitXMLEditor\bin\Debug
  name: GranitEditor Debug Deployment
deploy:
- provider: Environment
  name: GranitEditor Releases Environment
  on:
    branch: master
