version: '{build}'
branches:
  only:
  - master

#skip_non_tags: true

# Including commits with particular message or from specific user
only_commits:
  message: /build/                # Start a new build if message contains 'build'

image: Visual Studio 2017

#environment:
  #IDE_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE

install:
  - ps: .\install-vsix-appveyor.ps1

configuration:
- Release
- Debug
platform: Any CPU
build:
  verbosity: detailed

  # scripts to run after build
#after_build:
  #- ps: $($env:IDE_PATH)\devenv.exe GranitEditorSetup\GranitEditorSetup.vdproj /build $($env:CONFIGURATION)

artifacts:
- path: GranitEditorSetup\Release
  name: GranitEditor Installer
- path: GranitXMLEditor\bin\Release
  name: GranitEditor Release Deployment
- path: GranitXMLEditor\bin\Debug
  name: GranitEditor Debug Deployment
deploy:
- provider: Environment
  name: GranitEditor Releases Environment
  on:
    branch: master
