version: '{build}'
branches:
  only:
  - master

#skip_non_tags: true

# Including commits with particular message or from specific user
only_commits:
  message: /build/                # Start a new build if message contains 'build'

image: Visual Studio 2017

install:
  - ps: (new-object net.webclient).DownloadFile('https://visualstudiogallery.msdn.microsoft.com/fd136a01-a0c8-475f-94dd-240136f86746/file/247375/3/InstallerProjects.vsix', 'InstallerProjects.vsix')
  - cmd: set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE;%PATH%
  - cmd: VSIXInstaller.exe /q /a InstallerProjects.vsix

configuration:
- Release
- Debug
platform: Any CPU
build:
  verbosity: normal
artifacts:
- path: GranitEditorSetup\Release
  name: GranitEditor Installer
- path: GranitXMLEditor\bin\Release
  name: GranitEditor Release Deployment
- path: GranitXMLEditor\bin\Debug
  name: GranitEditor Debug Deployment
deploy:
- provider: Environment
  name: GranitEditor Releases Environment
  on:
    branch: master
